"""make national park state optional

Revision ID: 1dc332ba4c3f
Revises: d8bcaaed3a5b
Create Date: 2025-10-31 13:32:25.825231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dc332ba4c3f'
down_revision = 'd8bcaaed3a5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Only drop tables if they exist
    if 'user_interests' in existing_tables:
        op.drop_table('user_interests')
    if 'user_links' in existing_tables:
        op.drop_table('user_links')
    
    if 'temp_user_registrations' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('temp_user_registrations')]
        if 'ix_temp_user_registrations_email' in existing_indexes:
            op.drop_index(op.f('ix_temp_user_registrations_email'), table_name='temp_user_registrations')
        if 'ix_temp_user_registrations_username' in existing_indexes:
            op.drop_index(op.f('ix_temp_user_registrations_username'), table_name='temp_user_registrations')
        op.drop_table('temp_user_registrations')
    
    if 'national_parks' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('national_parks')]
        if 'ix_national_parks_name' in existing_indexes:
            op.drop_index(op.f('ix_national_parks_name'), table_name='national_parks')
        if 'ix_national_parks_slug' in existing_indexes:
            op.drop_index(op.f('ix_national_parks_slug'), table_name='national_parks')
        op.drop_table('national_parks')
    
    if 'user_activity_stats' in existing_tables:
        op.drop_table('user_activity_stats')
    
    # Check if discussions table exists before modifying it
    if 'discussions' in existing_tables:
        op.alter_column('discussions', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
        op.alter_column('discussions', 'content_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
        
        # Check and drop constraint if exists
        existing_constraints = [c['name'] for c in inspector.get_unique_constraints('discussions')]
        if 'discussions_slug_key' in existing_constraints:
            op.drop_constraint(op.f('discussions_slug_key'), 'discussions', type_='unique')
        
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('discussions')]
        if 'ix_discussions_slug' in existing_indexes:
            op.drop_index(op.f('ix_discussions_slug'), table_name='discussions')
        
        op.create_index(op.f('ix_discussions_slug'), 'discussions', ['slug'], unique=True)
    
    # Check if user_badge_assignments table exists
    if 'user_badge_assignments' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('user_badge_assignments')]
        if 'ix_user_badge_assignments_badge_id' not in existing_indexes:
            op.create_index(op.f('ix_user_badge_assignments_badge_id'), 'user_badge_assignments', ['badge_id'], unique=False)
        if 'ix_user_badge_assignments_user_id' not in existing_indexes:
            op.create_index(op.f('ix_user_badge_assignments_user_id'), 'user_badge_assignments', ['user_id'], unique=False)
    
    # Check if user_badges table exists
    if 'user_badges' in existing_tables:
        existing_constraints = [c['name'] for c in inspector.get_unique_constraints('user_badges')]
        if 'user_badges_name_key' in existing_constraints:
            op.drop_constraint(op.f('user_badges_name_key'), 'user_badges', type_='unique')
        if 'user_badges_slug_key' in existing_constraints:
            op.drop_constraint(op.f('user_badges_slug_key'), 'user_badges', type_='unique')
        
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('user_badges')]
        if 'ix_user_badges_name' in existing_indexes:
            op.drop_index(op.f('ix_user_badges_name'), table_name='user_badges')
        op.create_index(op.f('ix_user_badges_name'), 'user_badges', ['name'], unique=True)
        
        if 'ix_user_badges_slug' in existing_indexes:
            op.drop_index(op.f('ix_user_badges_slug'), table_name='user_badges')
        op.create_index(op.f('ix_user_badges_slug'), 'user_badges', ['slug'], unique=True)
    
    # Check users table indexes
    if 'users' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        if 'ix_users_facebook_id' in existing_indexes:
            op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
        if 'ix_users_google_id' in existing_indexes:
            op.drop_index(op.f('ix_users_google_id'), table_name='users')
        if 'ix_users_linkedin_id' in existing_indexes:
            op.drop_index(op.f('ix_users_linkedin_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_linkedin_id'), 'users', ['linkedin_id'], unique=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=False)
    op.drop_index(op.f('ix_user_badges_slug'), table_name='user_badges')
    op.create_index(op.f('ix_user_badges_slug'), 'user_badges', ['slug'], unique=False)
    op.drop_index(op.f('ix_user_badges_name'), table_name='user_badges')
    op.create_index(op.f('ix_user_badges_name'), 'user_badges', ['name'], unique=False)
    op.create_unique_constraint(op.f('user_badges_slug_key'), 'user_badges', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_badges_name_key'), 'user_badges', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_badge_assignments_user_id'), table_name='user_badge_assignments')
    op.drop_index(op.f('ix_user_badge_assignments_badge_id'), table_name='user_badge_assignments')
    op.drop_index(op.f('ix_discussions_slug'), table_name='discussions')
    op.create_index(op.f('ix_discussions_slug'), 'discussions', ['slug'], unique=False)
    op.create_unique_constraint(op.f('discussions_slug_key'), 'discussions', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('discussions', 'content_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discussions', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_table('user_activity_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('posts_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saved_podcasts_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saved_photos_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quizzes_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activity_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_stats')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_activity_stats_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('national_parks',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_national_parks')),
    sa.UniqueConstraint('name', name=op.f('uq_national_parks_name'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name=op.f('uq_national_parks_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_national_parks_slug'), 'national_parks', ['slug'], unique=False)
    op.create_index(op.f('ix_national_parks_name'), 'national_parks', ['name'], unique=False)
    op.create_table('temp_user_registrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email_verification_token', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('email_verification_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_user_registrations'))
    )
    op.create_index(op.f('ix_temp_user_registrations_username'), 'temp_user_registrations', ['username'], unique=True)
    op.create_index(op.f('ix_temp_user_registrations_email'), 'temp_user_registrations', ['email'], unique=True)
    op.create_table('user_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_links'))
    )
    op.create_table('user_interests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interest_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_interests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_interests')),
    sa.UniqueConstraint('user_id', 'interest_name', name=op.f('unique_user_interest'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###