"""add_user_profile_and_verification_fields

Revision ID: 64214129c28e
Revises: 6c0064402e1d
Create Date: 2025-09-04 17:13:04.457767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64214129c28e'
down_revision = '6c0064402e1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    from sqlalchemy.dialects import postgresql
    
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    # Check if users table exists before trying to modify it
    if 'users' not in tables:
        print("⚠️  Skipping: users table does not exist yet")
        return
    
    # Get existing columns in users table
    existing_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'full_name' not in existing_columns:
        op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    
    if 'gender' not in existing_columns:
        # Create the ENUM type first if it doesn't exist
        gender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='genderenum', create_type=False)
        gender_enum.create(conn, checkfirst=True)
        
        # Now add the column using the created ENUM
        op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='genderenum', create_type=False), nullable=True))
    
    if 'country' not in existing_columns:
        op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    
    if 'bio' not in existing_columns:
        op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    
    if 'avatar_url' not in existing_columns:
        op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    
    # Add is_email_verified with default value, then set to NOT NULL
    if 'is_email_verified' not in existing_columns:
        op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        op.execute("UPDATE users SET is_email_verified = false WHERE is_email_verified IS NULL")
        op.alter_column('users', 'is_email_verified', nullable=False)
    
    if 'email_verification_token' not in existing_columns:
        op.add_column('users', sa.Column('email_verification_token', sa.String(length=100), nullable=True))
    
    if 'email_verification_expires' not in existing_columns:
        op.add_column('users', sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True))
    
    if 'password_reset_token' not in existing_columns:
        op.add_column('users', sa.Column('password_reset_token', sa.String(length=100), nullable=True))
    
    if 'password_reset_expires' not in existing_columns:
        op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    
    if 'preferences' not in existing_columns:
        op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    
    if 'last_login' not in existing_columns:
        op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    conn = op.get_bind()
    
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'email_verification_expires')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'country')
    op.drop_column('users', 'gender')
    
    # Drop the ENUM type (if no other tables use it)
    try:
        gender_enum = postgresql.ENUM(name='genderenum')
        gender_enum.drop(conn, checkfirst=True)
    except Exception as e:
        print(f"Could not drop genderenum type: {e}")
    # ### end Alembic commands ###
