"""Add temporary user registration table

Revision ID: bc95c2de78e7
Revises: 64214129c28e
Create Date: 2025-09-06 16:30:20.453912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc95c2de78e7'
down_revision = '64214129c28e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
